### ISSUE TITLE
Some sprites are being rendered too high

### ISSUE THREAD

**Issue by donno2048** [aMoniker/Gush#4]
![image](https://user-images.githubusercontent.com/61805754/131558257-25288ba6-3ba4-4ed7-9dff-3f5a032346e2.png)

**Comment by aMoniker** [comment]
Yeah, this is an artifact of how game objects are created/destroyed on the fly in order to maintain a decent framerate.
One solution might be to call `readd` on all monsters after any new tiles are drawn. That changes the monster's `_id` though, so the hit-detection code in each weapon should probably also be updated to not rely on `_id` if possible.

https://github.com/aMoniker/Gush/blob/master/levels/visibility.js#L121

**Comment by donno2048** [comment]
Stale
